
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyfqnasuvknnvrslwsiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5ZnFuYXN1dmtubnZyc2x3c2l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMjExODMsImV4cCI6MjA1NDc5NzE4M30.AxVTTt8HpDpcS1Fqqy7ItyOwF8fKLazPgLLvaQ8wgYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    detectSessionInUrl: true,
    autoRefreshToken: true
  },
  global: {
    headers: {
      'X-Client-Info': 'lovable-dashboard-app'
    }
  },
  db: {
    schema: 'public'
  }
});

// Check the connection by fetching a simple query
supabase.from('team_leads').select('count').limit(1).single()
  .then(() => {
    console.log('Successfully connected to Supabase');
  })
  .catch((error: any) => {
    console.error('Failed to connect to Supabase:', error);
  });
