// This file is automatically generated. Do not edit it directly.

import { Pool } from "pg";

// Update these values to match your local Postgres setup
const pool = new Pool({
  user: "cx_user",
  host: "10.169.39.64",
  database: "cx_dashboard_db",
  password: "@lquid#pass321",
  port: 5432, // default Postgres port
});